name: Run tests
on: push
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/tiruka_fib_py" >> $GITHUB_ENV
      - name: run tests
        run: python -m unittest discover ./tests
      - name: run type checking
        run: mypy tiruka_fib_py
